pip install litserve
pip install torch
pip install torchvision
pip install pillow
pip install numpy
pip install typing
pip install scikit-image
pip install huggingface_hub
pip install "transformers>=4.39.1"
pip install flask